// This file is an AUTOGENERATED part of quicksave project.
// Copyright (c) 2017 Aleksander Gajewski <adiog@quicksave.io>.

const env = {
    HTTPS_API_QUICKSAVE_IO: 'http://api.quicksave.io',
    HTTPS_CDN_QUICKSAVE_IO: 'http://cdn.quicksave.io',
    HTTPS_OAUTH_QUICKSAVE_IO: 'http://oauth.quicksave.io',
};
